Name:           perl-TAP-Harness-JUnit
Version:        0.23
Release:        0.2%{?dist}
Summary:        Generate JUnit compatible output from TAP results
License:        GPL+ or Artistic
Group:          Development/Libraries

URL:            http://search.cpan.org/dist/TAP-Harness-JUnit/
Source0:        http://www.cpan.org/authors/id/L/LK/LKUNDRAK/TAP-Harness-JUnit-%{version}.tar.gz

BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
Requires:       perl(TAP::Harness) >= 3.05
BuildRequires:  perl(File::Temp)  
BuildRequires:  perl(Scalar::Util)  
BuildRequires:  perl(TAP::Harness) >= 3.05
BuildRequires:  perl(TAP::Parser)  
BuildRequires:  perl(XML::Simple)  
BuildRequires:  perl(TAP::Harness)  
BuildRequires:  perl(Test::More)  
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The only difference between this module and TAP::Harness is that this adds
mandatory 'xmlfile' argument, that causes the output to be formatted into
XML in format similar to one that is produced by JUnit testing framework.


%prep
%setup -q -n TAP-Harness-JUnit-%{version}


%build
%{__perl} Build.PL installdirs=vendor
./Build


%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*


%check
./Build test


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%doc README
%{perl_vendorlib}/*
%{_mandir}/man3/*


%changelog
* Tue Aug 19 2008 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> 0.22-1
- New upstream release
- Enhanced documentation
- Fixed handling of tests with bad plan
- Ignore SKIP and TODO tests in JUnit

* Wed Aug 06 2008 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> 0.21-2
- Add BRs for enabled tests

* Wed Aug 06 2008 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> 0.21-1
- New usptream release

* Thu Jul 31 2008 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> 0.20-1
- New usptream release

* Wed Jul 30 2008 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> 0.01-2
- Allow test names to be specified without comments

* Mon Jul 28 2008 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> 0.01-1
- Specfile autogenerated by cpanspec 1.75.
- Fixed requires
